# Generated by Django 4.2.4 on 2023-08-09 13:57

from django.db import migrations
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.CustomUserManager()),
            ],
        ),
    ]
